# Generated by Django 4.1.3 on 2022-12-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaRoll_app', '0002_manger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='image',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='pdf',
            new_name='pdfs',
        ),
        migrations.AlterField(
            model_name='manga',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='manger',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='mangaRoll_app/static'),
        ),
    ]
