# Generated by Django 4.1.3 on 2022-12-18 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaRoll_app', '0006_alter_manga_images_alter_manga_pdfs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='pdfs',
        ),
    ]
