# Generated by Django 4.1.3 on 2022-12-18 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaRoll_app', '0008_rename_images_manga_manga_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='manga_images',
            new_name='this_images',
        ),
    ]
