# Generated by Django 4.1.3 on 2022-12-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaRoll_app', '0010_rename_this_images_manga_this_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='this_pdf',
            field=models.FileField(blank=True, upload_to='mangaroll-image'),
        ),
    ]
